Repository codesquad-members-2021/sidedish, pull requests merged in 2021-04, with the labels that each got.

#2 [Beemo, ppamppam] side-dish FE 1주차 PR 01
  .gitignore
  BE-ReadME.md
  BE/p.txt
  FE-ReadME.md
  FE/package.json
  FE/public/favicon.ico
  FE/public/index.html
  FE/public/logo192.png
  FE/public/logo512.png
  FE/public/manifest.json
  FE/public/robots.txt
  FE/src/App.js
  FE/src/Components/Carousel/CarouselButton.js
  FE/src/Components/Carousel/CarouselContainer.js
  FE/src/Components/Carousel/CarouselItem.js
  FE/src/Components/Carousel/index.js
  FE/src/Components/Header/Dropdown/Dropdown.js
  FE/src/Components/Header/Header.js
  FE/src/Components/Header/Navigation/Navigation.js
  FE/src/Components/Header/SearchBar/SearchBar.js
  FE/src/Components/commons/Button.js
  FE/src/Components/commons/Buttons/LeftArrowButtonActive.js
  FE/src/Components/commons/Buttons/RightArrowButtonActive.js
  FE/src/Components/commons/Card.js
  FE/src/Components/commons/styledComponents.js
  FE/src/Pages/MainPage.js
  FE/src/images/LeftArrowButtonDeactive.svg
  FE/src/images/RightArrowButtonDeactive.svg
  FE/src/images/magnifyingGlass.svg
  FE/src/index.css
  FE/src/index.js
  FE/src/util/actions/test-action.js
  FE/src/util/hooks/test-useXX.js
  README.md
Labels: review-FE

#4 [Team23] 컴포넌트 트리 구조 추가 및 수정, 범용 Button, Label, Card 생성, Header, CarouselSection 생성
  banchan/.gitignore
  banchan/README.md
  banchan/package-lock.json
  banchan/package.json
  banchan/public/favicon.ico
  banchan/public/index.html
  banchan/src/App.css
  banchan/src/App.jsx
  banchan/src/App.test.js
  banchan/src/components/StateProvider.jsx
  banchan/src/components/header/Header.jsx
  banchan/src/components/header/headerLeft/HeaderLeft.jsx
  banchan/src/components/header/headerLeft/HeaderNavbar.jsx
  banchan/src/components/header/headerLeft/NavListItems.jsx
  banchan/src/components/header/headerRight/HeaderRight.jsx
  banchan/src/components/main/BestSidedish.jsx
  banchan/src/components/main/CarouselSection.jsx
  banchan/src/components/main/CarouselSectionList.jsx
  banchan/src/components/main/MainPage.jsx
  banchan/src/components/utils/Card.jsx
  banchan/src/components/utils/Label.jsx
  banchan/src/components/utils/Price.jsx
  banchan/src/components/utils/button/Button.jsx
  banchan/src/components/utils/button/IconButton.jsx
  banchan/src/components/utils/button/TextButton.jsx
  banchan/src/components/utils/constant.js
  banchan/src/index.css
  banchan/src/index.js
  banchan/yarn.lock
  package-lock.json
Labels: review-FE

#5 [ FE ] [ DDeong ] 월, 화 진행 사항
  .gitignore
  README.md
  package-lock.json
  package.json
  public/index.html
  src/App.js
  src/index.css
  src/index.js
  src/js/components/Modal/Modal.js
  src/js/components/Modal/Order.js
  src/js/components/Modal/ThumbNail.js
  src/js/components/Section/Article.js
  src/js/components/bestList/BestList.jsx
  src/js/components/common/Badge.jsx
  src/js/components/common/Button.js
  src/js/components/common/Card.jsx
  src/js/components/header.js
  src/js/util/Carousel.js
  src/js/util/TestCarousel.js
  src/reportWebVitals.js
  src/setupTests.js
  webapck.dev.js
  yarn.lock
Labels: review-FE

#11 [Goody Kyle] 메인화면 UI
  .vscode/settings.json
  sidedish/.gitignore
  sidedish/.prettierrc.js
  sidedish/README.md
  sidedish/jsconfig.json
  sidedish/package-lock.json
  sidedish/package.json
  sidedish/public/index.html
  sidedish/src/App.css
  sidedish/src/App.js
  sidedish/src/component/BestSidedish/BestSidedish.jsx
  sidedish/src/component/BestSidedish/BestSidedishList/BestSidedishList.jsx
  sidedish/src/component/BestSidedish/BestTabList/BestTab.jsx
  sidedish/src/component/BestSidedish/BestTabList/BestTabList.jsx
  sidedish/src/component/DishItem/DishHover.jsx
  sidedish/src/component/DishItem/DishItem.jsx
  sidedish/src/component/Header/CartButton.jsx
  sidedish/src/component/Header/Header.jsx
  sidedish/src/component/Header/LoginButton.jsx
  sidedish/src/component/Header/Logo.jsx
  sidedish/src/component/Header/Search.jsx
  sidedish/src/component/Header/Tab.jsx
  sidedish/src/component/Main/Main.jsx
  sidedish/src/component/SlideDish/SlideDish.jsx
  sidedish/src/component/atoms/MoreButton.jsx
  sidedish/src/fetchData.js
  sidedish/src/hooks/useFetch.js
  sidedish/src/index.css
  sidedish/src/index.js
  sidedish/src/theme.js
  sidedish/src/util/data.js
Labels: review-FE

#17 [Team23] Tab section 구현, 컴포넌트 트리 구조 추가
  banchan/src/App.jsx
  banchan/src/components/StateProvider.jsx
  banchan/src/components/header/Header.jsx
  banchan/src/components/header/headerLeft/HeaderLeft.jsx
  banchan/src/components/header/headerLeft/HeaderNavbar.jsx
  banchan/src/components/header/headerLeft/NavListItems.jsx
  banchan/src/components/header/headerRight/HeaderRight.jsx
  banchan/src/components/main/BestSidedish.jsx
  banchan/src/components/main/CarouselSection.jsx
  banchan/src/components/main/MainPage.jsx
  banchan/src/components/main/tab/TabSection.jsx
  banchan/src/components/utils/Card.jsx
  banchan/src/components/utils/Label.jsx
  banchan/src/components/utils/Price.jsx
  banchan/src/components/utils/button/IconButton.jsx
  banchan/src/components/utils/button/TextButton.jsx
  banchan/src/components/utils/constant.js
  banchan/src/components/utils/styles/common.jsx
  banchan/src/components/utils/styles/theme.js
  banchan/src/components/utils/variables.js
  banchan/src/index.css
  banchan/src/index.js
Labels: review-FE

#28 [iOS][Aiden, BMO] team-07 sideDish 1주차 PR 01
  backend/README.md
  frontend/README.md
  frontend/SideDish/SideDish.xcodeproj/project.pbxproj
  frontend/SideDish/SideDish.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  frontend/SideDish/SideDish.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  frontend/SideDish/SideDish.xcodeproj/project.xcworkspace/xcuserdata/sonjuhyeong.xcuserdatad/UserInterfaceState.xcuserstate
  frontend/SideDish/SideDish.xcodeproj/xcuserdata/sonjuhyeong.xcuserdatad/xcschemes/xcschememanagement.plist
  frontend/SideDish/SideDish.xcodeproj/xcuserdata/user.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
  frontend/SideDish/SideDish/AppCycle/AppDelegate.swift
  frontend/SideDish/SideDish/AppCycle/SceneDelegate.swift
  frontend/SideDish/SideDish/Assets.xcassets/AccentColor.colorset/Contents.json
  frontend/SideDish/SideDish/Assets.xcassets/AppIcon.appiconset/Contents.json
  frontend/SideDish/SideDish/Assets.xcassets/Contents.json
  frontend/SideDish/SideDish/Base.lproj/LaunchScreen.storyboard
  frontend/SideDish/SideDish/Base.lproj/Main.storyboard
  frontend/SideDish/SideDish/Info.plist
  frontend/SideDish/SideDish/Model/DTO/JSONModel.swift
  frontend/SideDish/SideDish/Model/DTO/Network.swift
  frontend/SideDish/SideDish/Model/DTO/Parsing.swift
  frontend/SideDish/SideDish/Model/Menu.swift
  frontend/SideDish/SideDish/Model/MenuCellValidater.swift
  frontend/SideDish/SideDish/Model/Menus.swift
  frontend/SideDish/SideDish/View/HeaderView.swift
  frontend/SideDish/SideDish/View/HeaderView.xib
  frontend/SideDish/SideDish/View/MainDiffableDataSource.swift
  frontend/SideDish/SideDish/View/MenuCell.swift
  frontend/SideDish/SideDish/View/MenuCell.xib
  frontend/SideDish/SideDish/ViewController.swift
  frontend/SideDish/SideDish/ViewModel/MenuViewModel.swift
  frontend/SideDish/SideDish/ViewModel/MenusViewModel.swift
  frontend/SideDish/SideDishTests/Info.plist
  frontend/SideDish/SideDishTests/SideDishTests.swift
  frontend/SideDish/SideDishUITests/Info.plist
  frontend/SideDish/SideDishUITests/SideDishUITests.swift
Labels: review-iOS

#19 [ DDeong ] 1차 완성 / Carousel npm 배포
  .vscode/launch.json
  package-lock.json
  package.json
  src/App.js
  src/js/components/Header.jsx
  src/js/components/Main.jsx
  src/js/components/Modal/Modal.js
  src/js/components/Modal/Modal.jsx
  src/js/components/Modal/ThumbNail.js
  src/js/components/Modal/ThumbNail.jsx
  src/js/components/bestList/BestList.jsx
  src/js/components/common/Badge.jsx
  src/js/components/common/Button.js
  src/js/components/common/Button.jsx
  src/js/components/common/Card.jsx
  src/js/components/header.js
  src/js/util/Carousel.js
  src/js/util/TestCarousel.js
  webapck.dev.js
Labels: review-FE

#18 [Team-21] RaQQoon Sidedish
  raqqoon-sidedish/.env
  raqqoon-sidedish/.gitignore
  raqqoon-sidedish/README.md
  raqqoon-sidedish/jsconfig.json
  raqqoon-sidedish/package-lock.json
  raqqoon-sidedish/package.json
  raqqoon-sidedish/public/index.html
  raqqoon-sidedish/public/robots.txt
  raqqoon-sidedish/src/App.js
  raqqoon-sidedish/src/App.test.js
  raqqoon-sidedish/src/components/Card/Card.jsx
  raqqoon-sidedish/src/components/Card/Img.jsx
  raqqoon-sidedish/src/components/Card/Info.jsx
  raqqoon-sidedish/src/components/Card/Price.jsx
  raqqoon-sidedish/src/components/Card/Tag.jsx
  raqqoon-sidedish/src/components/Carousel/Carousel.jsx
  raqqoon-sidedish/src/components/Carousel/CarouselContainer.jsx
  raqqoon-sidedish/src/components/Carousel/CarouselSection.jsx
  raqqoon-sidedish/src/components/Header.jsx
  raqqoon-sidedish/src/components/Main.jsx
  raqqoon-sidedish/src/components/Nav/Dropdown.jsx
  raqqoon-sidedish/src/components/Nav/Menu.jsx
  raqqoon-sidedish/src/components/Nav/MenuList.jsx
  raqqoon-sidedish/src/components/TabUI/Tab.jsx
  raqqoon-sidedish/src/components/TabUI/TabBody.jsx
  raqqoon-sidedish/src/components/TabUI/TabHeader.jsx
  raqqoon-sidedish/src/components/TabUI/TabList.jsx
  raqqoon-sidedish/src/components/TabUI/TabMain.jsx
  raqqoon-sidedish/src/components/TabUI/TabTitle.jsx
  raqqoon-sidedish/src/components/TabUI/TabUI.jsx
  raqqoon-sidedish/src/components/icons/Arrow.jsx
  raqqoon-sidedish/src/const.js
  raqqoon-sidedish/src/customHooks/useFetch.js
  raqqoon-sidedish/src/customHooks/useTab.js
  raqqoon-sidedish/src/index.css
  raqqoon-sidedish/src/index.js
  raqqoon-sidedish/src/reportWebVitals.js
  raqqoon-sidedish/src/reset.css
  raqqoon-sidedish/src/setupTests.js
  raqqoon-sidedish/yarn.lock
Labels: review-FE

#21 [Jangbagoony - FE- PR1]
  frontend/.env
  frontend/.gitignore
  frontend/README.md
  frontend/package-lock.json
  frontend/package.json
  frontend/public/favicon.ico
  frontend/public/index.html
  frontend/public/logo192.png
  frontend/public/logo512.png
  frontend/public/manifest.json
  frontend/public/robots.txt
  frontend/src/App.css
  frontend/src/App.js
  frontend/src/App.test.js
  frontend/src/components/ItemCard.jsx
  frontend/src/components/Theme.jsx
  frontend/src/components/category/Category.jsx
  frontend/src/components/category/CategoryList.jsx
  frontend/src/components/category/CategorySlide.jsx
  frontend/src/components/detail/DetailPage.jsx
  frontend/src/components/detail/Payment.jsx
  frontend/src/components/header/Header.jsx
  frontend/src/components/header/HeaderLeft.jsx
  frontend/src/components/header/Login.jsx
  frontend/src/components/header/MenuTab.jsx
  frontend/src/components/header/ShoppingBag.jsx
  frontend/src/components/header/headerRight.jsx
  frontend/src/components/mainmenu/MainMenu.jsx
  frontend/src/components/mokdata.jsx
  frontend/src/components/useFetch.jsx
  frontend/src/index.css
  frontend/src/index.js
  frontend/src/logo.svg
  frontend/src/reportWebVitals.js
  frontend/src/setupTests.js
  frontend/yarn.lock
Labels: review-FE

#25 [Goody,Kyle] 캐러셀 구현 중...
  sidedish/src/App.js
  sidedish/src/component/BestSidedish/BestSidedish.jsx
  sidedish/src/component/BestSidedish/BestSidedishList/BestSidedishList.jsx
  sidedish/src/component/Carousel/Carousel.jsx
  sidedish/src/component/DishItem/DishItem.jsx
  sidedish/src/component/Header/Header.jsx
  sidedish/src/component/Header/Tab.jsx
  sidedish/src/component/Header/TabList.jsx
  sidedish/src/component/SlideDish/SlideDish.jsx
  sidedish/src/hooks/useFetch.js
  sidedish/src/util/data.js
Labels: review-FE

#26 [FE][Team17] 1주차 PR
  FE/banchan-project/.gitignore
  FE/banchan-project/package-lock.json
  FE/banchan-project/package.json
  FE/banchan-project/public/index.html
  FE/banchan-project/src/App.js
  FE/banchan-project/src/DetailModal/DetailModal.jsx
  FE/banchan-project/src/DetailModal/DetailModalStyles.jsx
  FE/banchan-project/src/DetailModal/DetailModalWindow/Count/Count.jsx
  FE/banchan-project/src/DetailModal/DetailModalWindow/Count/CountNumber.jsx
  FE/banchan-project/src/DetailModal/DetailModalWindow/Count/CountTitle.jsx
  FE/banchan-project/src/DetailModal/DetailModalWindow/Count/Counter.jsx
  FE/banchan-project/src/DetailModal/DetailModalWindow/Delivery/Delivery.jsx
  FE/banchan-project/src/DetailModal/DetailModalWindow/Delivery/DeliveryContents.jsx
  FE/banchan-project/src/DetailModal/DetailModalWindow/Delivery/DeliveryTitle.jsx
  FE/banchan-project/src/DetailModal/DetailModalWindow/DetailMainImage.jsx
  FE/banchan-project/src/DetailModal/DetailModalWindow/DetailModalWindow.jsx
  FE/banchan-project/src/DetailModal/DetailModalWindow/ItemInfo/DetailBadge.jsx
  FE/banchan-project/src/DetailModal/DetailModalWindow/ItemInfo/DetailDescription.jsx
  FE/banchan-project/src/DetailModal/DetailModalWindow/ItemInfo/DetailNPrice.jsx
  FE/banchan-project/src/DetailModal/DetailModalWindow/ItemInfo/DetailSPrice.jsx
  FE/banchan-project/src/DetailModal/DetailModalWindow/ItemInfo/DetailTitle.jsx
  FE/banchan-project/src/DetailModal/DetailModalWindow/ItemInfo/ItemInfo.jsx
  FE/banchan-project/src/DetailModal/DetailModalWindow/Prices/Prices.jsx
  FE/banchan-project/src/DetailModal/DetailModalWindow/Prices/SubmitButton.jsx
  FE/banchan-project/src/DetailModal/DetailModalWindow/Prices/TotalPrice.jsx
  FE/banchan-project/src/DetailModal/DetailModalWindow/Prices/TotalPriceDescription.jsx
  FE/banchan-project/src/DetailModal/DetailModalWindow/RecommendedItems/RecommendedItems.jsx
  FE/banchan-project/src/DetailModal/DetailModalWindow/RecommendedItems/RecommendedItemsCard/RecommendedItemsCard.jsx
  FE/banchan-project/src/DetailModal/DetailModalWindow/RecommendedItems/RecommendedItemsCard/RecommendedItemsCardImage.jsx
  FE/banchan-project/src/DetailModal/DetailModalWindow/RecommendedItems/RecommendedItemsCard/RecommendedItemsCardPrice.jsx
  FE/banchan-project/src/DetailModal/DetailModalWindow/RecommendedItems/RecommendedItemsCard/RecommendedItemsCardTitle.jsx
  FE/banchan-project/src/DetailModal/DetailModalWindow/RecommendedItems/RecommendedItemsPagination.jsx
  FE/banchan-project/src/DetailModal/DetailModalWindow/RecommendedItems/RecommendedItemsTitle.jsx
  FE/banchan-project/src/DetailModal/DetailModalWindow/ThumbNails/ThumbNails.jsx
  FE/banchan-project/src/DetailModal/DetailModalWindow/ThumbNails/ThumbNailsImage.jsx
  FE/banchan-project/src/MainItems/MainItems.jsx
  FE/banchan-project/src/MainItems/MainItemsCard/MainItemsCard.jsx
  FE/banchan-project/src/MainItems/MainItemsCard/MainItemsCardBadge.jsx
  FE/banchan-project/src/MainItems/MainItemsCard/MainItemsCardDescription.jsx
  FE/banchan-project/src/MainItems/MainItemsCard/MainItemsCardImage.jsx
  FE/banchan-project/src/MainItems/MainItemsCard/MainItemsCardNPrice.jsx
  FE/banchan-project/src/MainItems/MainItemsCard/MainItemsCardSPrice.jsx
  FE/banchan-project/src/MainItems/MainItemsCard/MainItemsCardTitle.jsx
  FE/banchan-project/src/MainItems/MainItemsStyles.jsx
  FE/banchan-project/src/MainItems/MainItemsTitle.jsx
  FE/banchan-project/src/MainItems/TotalCategoryButton.jsx
  FE/banchan-project/src/Styles/GlobalStyles.js
  FE/banchan-project/src/Styles/commonStyles.jsx
  FE/banchan-project/src/Styles/icons/LeftButton.svg
  FE/banchan-project/src/Styles/icons/RightButton.svg
  FE/banchan-project/src/Styles/icons/SearchButton.svg
  FE/banchan-project/src/Styles/icons/closeButton.svg
  FE/banchan-project/src/Styles/icons/downButton.svg
  FE/banchan-project/src/Styles/icons/upButton.svg
  FE/banchan-project/src/Styles/theme.js
  FE/banchan-project/src/index.js
  FE/banchan-project/src/utils/sortBadges.js
  README.md
Labels: review-FE

#30 [Team23] 캐로셀 적용, 모달창 설계 및 구현, 상품 이미지 호버 적용
  banchan/src/components/StateProvider.jsx
  banchan/src/components/main/CarouselList.jsx
  banchan/src/components/main/CarouselSection.jsx
  banchan/src/components/main/CarouselSectionList.jsx
  banchan/src/components/main/MainPage.jsx
  banchan/src/components/main/Modal.jsx
  banchan/src/components/main/tab/TabSection.jsx
  banchan/src/components/utils/Card.jsx
  banchan/src/components/utils/Price.jsx
  banchan/src/components/utils/button/IconButton.jsx
  banchan/src/components/utils/mockData.js
  banchan/src/components/utils/styles/common.jsx
  banchan/src/components/utils/variables.js
Labels: review-FE

#29 [team-13 FE] 1주차 PR
  fe/sidedish-fe/.gitignore
  fe/sidedish-fe/README.md
  fe/sidedish-fe/package-lock.json
  fe/sidedish-fe/package.json
  fe/sidedish-fe/public/index.html
  fe/sidedish-fe/src/App.css
  fe/sidedish-fe/src/App.js
  fe/sidedish-fe/src/components/BestMenu/BestMenu.jsx
  fe/sidedish-fe/src/components/BestMenu/BestMenu.style.jsx
  fe/sidedish-fe/src/components/BestMenu/BestMenuTab.jsx
  fe/sidedish-fe/src/components/Header/Dropdown.jsx
  fe/sidedish-fe/src/components/Header/Header.css
  fe/sidedish-fe/src/components/Header/Header.jsx
  fe/sidedish-fe/src/components/Header/Header.style.jsx
  fe/sidedish-fe/src/components/MenuCard/LargeCard.jsx
  fe/sidedish-fe/src/components/MenuCard/MenuCard.jsx
  fe/sidedish-fe/src/components/MenuCard/MenuCard.style.jsx
  fe/sidedish-fe/src/components/MenuCard/SmallCard.jsx
  fe/sidedish-fe/src/components/MenuDetailModal/MenuDetail/MenuDetail.js
  fe/sidedish-fe/src/components/MenuDetailModal/MenuDetail/OrderInfo/Counter.js
  fe/sidedish-fe/src/components/MenuDetailModal/MenuDetail/OrderInfo/OrderInfo.js
  fe/sidedish-fe/src/components/MenuDetailModal/MenuDetail/OrderInfo/SmallInfoContainer.js
  fe/sidedish-fe/src/components/MenuDetailModal/MenuDetail/Preview/Preview.js
  fe/sidedish-fe/src/components/MenuDetailModal/MenuDetail/RecommendSlider/RecommendSlider.js
  fe/sidedish-fe/src/components/MenuDetailModal/MenuDetailModal.js
  fe/sidedish-fe/src/components/MenuSliderContainer/MenuSlider/README.md
  fe/sidedish-fe/src/components/common/FlexContainer.jsx
  fe/sidedish-fe/src/components/common/Modal.js
  fe/sidedish-fe/src/components/common/Slider.js
  fe/sidedish-fe/src/components/common/badge.js
  fe/sidedish-fe/src/index.css
  fe/sidedish-fe/src/index.js
  fe/sidedish-fe/src/rsc/static/components.js
  fe/sidedish-fe/src/rsc/svg/downbtn.svg
  fe/sidedish-fe/src/rsc/svg/leftbtn.svg
  fe/sidedish-fe/src/rsc/svg/leftbtn_disabled.svg
  fe/sidedish-fe/src/rsc/svg/rightbtn.svg
  fe/sidedish-fe/src/rsc/svg/rightbtn_disabled.svg
  fe/sidedish-fe/src/rsc/svg/upbtn.svg
  fe/sidedish-fe/src/util/Global.js
  fe/sidedish-fe/src/util/hooks/useFetchData.js
Labels: review-FE

#31 [FE][Team19] Sidedish 1주차 PR
  .gitignore
  README.md
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  src/App.js
  src/api.js
  src/component/ShowMoreBtn.jsx
  src/component/bestTab/BestItems.jsx
  src/component/bestTab/BestTab.jsx
  src/component/bestTab/BestTabContainer.jsx
  src/component/bestTab/BestTabNavigator.jsx
  src/component/header/Header.jsx
  src/component/header/HeaderLeft.jsx
  src/component/header/HeaderRight.jsx
  src/component/header/Navigations.jsx
  src/component/popUp/PopUpContainer.jsx
  src/component/popUp/PopUpImages.jsx
  src/component/popUp/PopUpInformations.jsx
  src/component/slideContainer/SlideContainer.jsx
  src/component/slideContainer/SlideItems.jsx
  src/component/slideContainer/SliderArrowBtn.jsx
  src/component/util/ItemCard.jsx
  src/component/util/Label.jsx
  src/const.js
  src/index.css
  src/index.js
  src/style.js
Labels: review-FE

#6 [team-05][만사,V] 메인화면 구성 & MockAPI 연결
  .gitignore
  be/README.md
  ios/README.md
  ios/sidedishApp/sidedishApp.xcodeproj/project.pbxproj
  ios/sidedishApp/sidedishApp.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  ios/sidedishApp/sidedishApp.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  ios/sidedishApp/sidedishApp/AppDelegate.swift
  ios/sidedishApp/sidedishApp/Assets.xcassets/AccentColor.colorset/Contents.json
  ios/sidedishApp/sidedishApp/Assets.xcassets/AppIcon.appiconset/Contents.json
  ios/sidedishApp/sidedishApp/Assets.xcassets/Contents.json
  ios/sidedishApp/sidedishApp/Base.lproj/LaunchScreen.storyboard
  ios/sidedishApp/sidedishApp/Base.lproj/Main.storyboard
  ios/sidedishApp/sidedishApp/Data/Network/DetailNetworkManager.swift
  ios/sidedishApp/sidedishApp/Data/Network/Endpoint.swift
  ios/sidedishApp/sidedishApp/Data/Network/NetworkManager.swift
  ios/sidedishApp/sidedishApp/Data/Network/SidedishNetworkManager.swift
  ios/sidedishApp/sidedishApp/Domain/Entity/Category.swift
  ios/sidedishApp/sidedishApp/Domain/Entity/Detail.swift
  ios/sidedishApp/sidedishApp/Domain/Entity/DetailItem.swift
  ios/sidedishApp/sidedishApp/Domain/Entity/Item.swift
  ios/sidedishApp/sidedishApp/Domain/UseCase/DetailUseCase.swift
  ios/sidedishApp/sidedishApp/Domain/UseCase/DetailUseCasePort.swift
  ios/sidedishApp/sidedishApp/Domain/UseCase/SidedishFactory.swift
  ios/sidedishApp/sidedishApp/Domain/UseCase/SidedishUseCase.swift
  ios/sidedishApp/sidedishApp/Domain/UseCase/SidedishUseCasePort.swift
  ios/sidedishApp/sidedishApp/Info.plist
  ios/sidedishApp/sidedishApp/Presentation/UI/ViewControllers/DetailViewController.swift
  ios/sidedishApp/sidedishApp/Presentation/UI/ViewControllers/SidedishViewController.swift
  ios/sidedishApp/sidedishApp/Presentation/UI/Views/BadgeLabel.swift
  ios/sidedishApp/sidedishApp/Presentation/UI/Views/LayoutManager.swift
  ios/sidedishApp/sidedishApp/Presentation/UI/Views/RemoteImageView.swift
  ios/sidedishApp/sidedishApp/Presentation/UI/Views/SectionHeader.swift
  ios/sidedishApp/sidedishApp/Presentation/UI/Views/SidedishCell.swift
  ios/sidedishApp/sidedishApp/Presentation/ViewModels/DetailViewModel.swift
  ios/sidedishApp/sidedishApp/Presentation/ViewModels/DetailViewModelType.swift
  ios/sidedishApp/sidedishApp/Presentation/ViewModels/SidedishViewModel.swift
  ios/sidedishApp/sidedishApp/Presentation/ViewModels/SidedishViewModelType.swift
  ios/sidedishApp/sidedishApp/SceneDelegate.swift
  ios/sidedishApp/sidedishAppTests/Info.plist
  ios/sidedishApp/sidedishAppTests/sidedishAppTests.swift
  ios/sidedishApp/sidedishAppUITests/Info.plist
  ios/sidedishApp/sidedishAppUITests/sidedishAppUITests.swift
Labels: review-iOS

#32 [Team15 - FE] 1주차 PR
  frontend/.gitignore
  frontend/README.md
  frontend/package-lock.json
  frontend/package.json
  frontend/public/index.html
  frontend/src/App.js
  frontend/src/components/atoms/button/index.jsx
  frontend/src/components/atoms/icon/index.jsx
  frontend/src/components/atoms/image/index.jsx
  frontend/src/components/atoms/searchbar/index.jsx
  frontend/src/components/atoms/span/index.jsx
  frontend/src/components/atoms/tag/index.jsx
  frontend/src/components/molecules/HeaderLeft/index.jsx
  frontend/src/components/molecules/HeaderRight/index.jsx
  frontend/src/components/molecules/LargeCard/index.jsx
  frontend/src/components/molecules/MediumCard/index.jsx
  frontend/src/components/molecules/Tab/index.jsx
  frontend/src/components/organisms/BestDish/index.jsx
  frontend/src/components/organisms/Header/index.jsx
  frontend/src/components/organisms/ViewMore/index.jsx
  frontend/src/components/organisms/mainDish/index.jsx
  frontend/src/components/organisms/mainDish/index.style.jsx
  frontend/src/components/organisms/mainDish/slide.jsx
  frontend/src/images/close.svg
  frontend/src/images/down.svg
  frontend/src/images/left.svg
  frontend/src/images/right.svg
  frontend/src/images/search.svg
  frontend/src/images/up.svg
  frontend/src/index.js
  frontend/src/styles/reset.scss
  frontend/src/styles/style.scss
  frontend/src/util/useFetch.jsx
  frontend/src/util/useTaps.js
  sidedish/src/App.js
Labels: review-FE

#40 [Beemo, ppamppam] side-dish FE 2주차 PR 02
  FE/jsconfig.json
  FE/package.json
  FE/src/App.js
  FE/src/Components/Carousel/CarouselContainer.js
  FE/src/Components/Carousel/CarouselEventModal.js
  FE/src/Components/Carousel/CarouselItem.js
  FE/src/Components/Carousel/CarouselNavigator/CarouselButton.js
  FE/src/Components/Carousel/CarouselNavigator/CarouselIndex.js
  FE/src/Components/Carousel/CarouselNavigator/DefaultNavigator.js
  FE/src/Components/Carousel/CarouselNavigator/UpperNavigatior.js
  FE/src/Components/Carousel/CarouselNavigator/index.js
  FE/src/Components/Carousel/hooks/useCarousel.js
  FE/src/Components/Carousel/index.js
  FE/src/Components/Header/Dropdown/Dropdown.js
  FE/src/Components/Header/Header.js
  FE/src/Components/Header/Navigation/Navigation.js
  FE/src/Components/Header/SearchBar/SearchBar.js
  FE/src/Components/Modal/BottomSide/BottomSide.js
  FE/src/Components/Modal/DetailProductModal.js
  FE/src/Components/Modal/LeftSide/LeftSide.js
  FE/src/Components/Modal/LeftSide/SmallThumbnail.js
  FE/src/Components/Modal/LeftSide/Thumbnail.js
  FE/src/Components/Modal/RightSide/CountSelector.js
  FE/src/Components/Modal/RightSide/OrderButton.js
  FE/src/Components/Modal/RightSide/RightSide.js
  FE/src/Components/Modal/RightSide/Sum.js
  FE/src/Components/Tabs/Tabs.js
  FE/src/Components/commons/Card.js
  FE/src/Components/commons/Cards/ResponsiveCard.js
  FE/src/Components/commons/Cards/TabCard.js
  FE/src/Components/commons/Cards/index.js
  FE/src/Components/commons/SpecialLabelTag.js
  FE/src/Components/commons/base.js
  FE/src/Pages/MainPage.js
  FE/src/Pages/MainPage/MainDish/index.js
  FE/src/Pages/MainPage/index.js
  FE/src/images/BottomArrowButtonDeactive.svg
  FE/src/images/DisabledBottomArrowButtonDeactive.svg
  FE/src/images/TopArrowButtonDeactive.svg
  FE/src/images/close.svg
  FE/src/images/default.png
  FE/src/images/preparingImage.jpg
  FE/src/images/preparingProduct.png
  FE/src/index.js
  FE/src/util/API.js
  FE/src/util/hooks/test-useXX.js
  FE/src/util/hooks/useOnResize.js
  FE/src/util/hooks/useToggle.js
  FE/src/util/serviceUtils.js
Labels: review-FE

#22 [BE][Team-13][프레디, Starve] 목업 api 배포
  .gitignore
  README.md
  be/sidedish-be/.gitignore
  be/sidedish-be/build.gradle
  be/sidedish-be/gradle/wrapper/gradle-wrapper.jar
  be/sidedish-be/gradle/wrapper/gradle-wrapper.properties
  be/sidedish-be/gradlew
  be/sidedish-be/gradlew.bat
  be/sidedish-be/settings.gradle
  be/sidedish-be/src/main/java/com/codesquad/sidedish/SidedishBeApplication.java
  be/sidedish-be/src/main/java/com/codesquad/sidedish/utils/NotParsingJsonFileException.java
  be/sidedish-be/src/main/java/com/codesquad/sidedish/utils/NotReadJsonFileException.java
  be/sidedish-be/src/main/java/com/codesquad/sidedish/utils/SampleDataFactory.java
  be/sidedish-be/src/main/java/com/codesquad/sidedish/web/sidedish/DTO/DetailDTO.java
  be/sidedish-be/src/main/java/com/codesquad/sidedish/web/sidedish/DTO/DetailDataDTO.java
  be/sidedish-be/src/main/java/com/codesquad/sidedish/web/sidedish/DTO/ItemDTO.java
  be/sidedish-be/src/main/java/com/codesquad/sidedish/web/sidedish/DTO/SidedishDTO.java
  be/sidedish-be/src/main/java/com/codesquad/sidedish/web/sidedish/Price.java
  be/sidedish-be/src/main/java/com/codesquad/sidedish/web/sidedish/controller/BestSidedishController.java
  be/sidedish-be/src/main/java/com/codesquad/sidedish/web/sidedish/controller/CourseSidedishController.java
  be/sidedish-be/src/main/java/com/codesquad/sidedish/web/sidedish/controller/DetailController.java
  be/sidedish-be/src/main/java/com/codesquad/sidedish/web/sidedish/controller/MainSidedishController.java
  be/sidedish-be/src/main/java/com/codesquad/sidedish/web/sidedish/controller/SideSidedishesController.java
  be/sidedish-be/src/main/java/com/codesquad/sidedish/web/sidedish/controller/SoupSidedishController.java
  be/sidedish-be/src/main/resources/application-default.properties
  be/sidedish-be/src/main/resources/application-prod.properties
  be/sidedish-be/src/main/resources/common.properties
  be/sidedish-be/src/main/resources/data.sql
  be/sidedish-be/src/main/resources/sample-data/best-sidedishes.json
  be/sidedish-be/src/main/resources/sample-data/course-sidedishes.json
  be/sidedish-be/src/main/resources/sample-data/details.json
  be/sidedish-be/src/main/resources/sample-data/main-sidedishes.json
  be/sidedish-be/src/main/resources/sample-data/side-sidedishes.json
  be/sidedish-be/src/main/resources/sample-data/soup-sidedishes.json
  be/sidedish-be/src/main/resources/schema.sql
  be/sidedish-be/src/test/java/com/codesquad/sidedish/utils/SampleDataFactoryTest.java
  be/sidedish-be/src/test/java/com/codesquad/sidedish/web/sidedish/DetailDTOTestResults.java
  be/sidedish-be/src/test/java/com/codesquad/sidedish/web/sidedish/ItemDTOTestResults.java
  be/sidedish-be/src/test/java/com/codesquad/sidedish/web/sidedish/SidedishDTOTestResults.java
Labels: review-BE

#35 [Team10-BE] 상품조회 구현
  BE/.gitignore
  BE/build.gradle
  BE/gradle/wrapper/gradle-wrapper.jar
  BE/gradle/wrapper/gradle-wrapper.properties
  BE/gradlew
  BE/gradlew.bat
  BE/settings.gradle
  BE/src/main/java/com/team10/banchan/BanchanApplication.java
  BE/src/main/java/com/team10/banchan/controller/ItemDetailController.java
  BE/src/main/java/com/team10/banchan/controller/SectionController.java
  BE/src/main/java/com/team10/banchan/dto/ItemDetail.java
  BE/src/main/java/com/team10/banchan/dto/ItemDetailResponse.java
  BE/src/main/java/com/team10/banchan/dto/ItemSummary.java
  BE/src/main/java/com/team10/banchan/exception/NotFoundException.java
  BE/src/main/java/com/team10/banchan/model/Badge.java
  BE/src/main/java/com/team10/banchan/model/Category.java
  BE/src/main/java/com/team10/banchan/model/DeliveryDay.java
  BE/src/main/java/com/team10/banchan/model/DeliveryType.java
  BE/src/main/java/com/team10/banchan/model/Description.java
  BE/src/main/java/com/team10/banchan/model/DetailSection.java
  BE/src/main/java/com/team10/banchan/model/Item.java
  BE/src/main/java/com/team10/banchan/model/ItemImages.java
  BE/src/main/java/com/team10/banchan/model/Prices.java
  BE/src/main/java/com/team10/banchan/model/Section.java
  BE/src/main/java/com/team10/banchan/model/ThumbImage.java
  BE/src/main/java/com/team10/banchan/repository/CategoryRepository.java
  BE/src/main/java/com/team10/banchan/repository/ItemRepository.java
  BE/src/main/java/com/team10/banchan/repository/SectionRepository.java
  BE/src/main/java/com/team10/banchan/response/ResponseBody.java
  BE/src/main/java/com/team10/banchan/service/ItemDetailService.java
  BE/src/main/java/com/team10/banchan/service/SectionService.java
  BE/src/main/resources/application.properties
  BE/src/main/resources/schema.sql
  BE/src/test/java/com/team10/banchan/BanchanApplicationTests.java
  BE/src/test/java/com/team10/banchan/model/PricesTest.java
  BE/src/test/java/com/team10/banchan/repository/ItemRepositoryTest.java
  BE/src/test/java/com/team10/banchan/repository/SectionRepositoryTest.java
  BE/src/test/resources/application.properties
  BE/src/test/resources/data.sql
  README.md
Labels: review-BE

#34 [Jangbagoony 이노 & MJ] db 스키마 작성, API 구현
  .gitignore
  BE/.gitignore
  BE/build.gradle
  BE/gradle/wrapper/gradle-wrapper.jar
  BE/gradle/wrapper/gradle-wrapper.properties
  BE/gradlew
  BE/gradlew.bat
  BE/settings.gradle
  BE/src/main/java/com/mj_eno/sidedish/SideDishApplication.java
  BE/src/main/java/com/mj_eno/sidedish/config/MyCorsFilter.java
  BE/src/main/java/com/mj_eno/sidedish/config/RequestLoggingFilterConfig.java
  BE/src/main/java/com/mj_eno/sidedish/domain/Image/Image.java
  BE/src/main/java/com/mj_eno/sidedish/domain/Image/ImageRepository.java
  BE/src/main/java/com/mj_eno/sidedish/domain/badge/Badge.java
  BE/src/main/java/com/mj_eno/sidedish/domain/badge/BadgeRepository.java
  BE/src/main/java/com/mj_eno/sidedish/domain/bestMenuCategory/BestMenuCategory.java
  BE/src/main/java/com/mj_eno/sidedish/domain/bestMenuCategory/BestMenuCategoryRepository.java
  BE/src/main/java/com/mj_eno/sidedish/domain/detailImage/DetailImage.java
  BE/src/main/java/com/mj_eno/sidedish/domain/detailImage/DetailImageRepository.java
  BE/src/main/java/com/mj_eno/sidedish/domain/dish/Delivery.java
  BE/src/main/java/com/mj_eno/sidedish/domain/dish/Dish.java
  BE/src/main/java/com/mj_eno/sidedish/domain/dish/DishRepository.java
  BE/src/main/java/com/mj_eno/sidedish/domain/dish/Price.java
  BE/src/main/java/com/mj_eno/sidedish/domain/dishBadge/DishBadge.java
  BE/src/main/java/com/mj_eno/sidedish/domain/dishBadge/DishBadgeRepository.java
  BE/src/main/java/com/mj_eno/sidedish/domain/menuCategory/MenuCategory.java
  BE/src/main/java/com/mj_eno/sidedish/domain/menuCategory/MenuCategoryRepository.java
  BE/src/main/java/com/mj_eno/sidedish/exception/EntityNotFoundException.java
  BE/src/main/java/com/mj_eno/sidedish/exception/ErrorMessage.java
  BE/src/main/java/com/mj_eno/sidedish/exception/OrderFailedException.java
  BE/src/main/java/com/mj_eno/sidedish/service/BadgeService.java
  BE/src/main/java/com/mj_eno/sidedish/service/CategoryService.java
  BE/src/main/java/com/mj_eno/sidedish/service/DishService.java
  BE/src/main/java/com/mj_eno/sidedish/service/ImageService.java
  BE/src/main/java/com/mj_eno/sidedish/web/DishController.java
  BE/src/main/java/com/mj_eno/sidedish/web/dto/BestDishResponseDTO.java
  BE/src/main/java/com/mj_eno/sidedish/web/dto/DetailDishDTO.java
  BE/src/main/java/com/mj_eno/sidedish/web/dto/DetailDishResponseDTO.java
  BE/src/main/java/com/mj_eno/sidedish/web/dto/DishResponseDTO.java
  BE/src/main/java/com/mj_eno/sidedish/web/dto/OrderDishRequestDTO.java
  BE/src/main/java/com/mj_eno/sidedish/web/dto/OrderDishResponseDTO.java
  BE/src/main/resources/application.properties
  BE/src/main/resources/data.sql
  BE/src/main/resources/schema.sql
  BE/src/test/java/com/mj_eno/sidedish/SideDishApplicationTests.java
Labels: review-BE

#47 [BE][Team14 - 새리, Dong] 1차 PR
  BE/p.txt
  BE/side-dish-backend/.gitignore
  BE/side-dish-backend/build.gradle
  BE/side-dish-backend/gradle/wrapper/gradle-wrapper.jar
  BE/side-dish-backend/gradle/wrapper/gradle-wrapper.properties
  BE/side-dish-backend/gradlew
  BE/side-dish-backend/gradlew.bat
  BE/side-dish-backend/settings.gradle
  BE/side-dish-backend/src/main/java/com/codesquad/team14/SideDishBackendApplication.java
  BE/side-dish-backend/src/main/java/com/codesquad/team14/controller/CategoryController.java
  BE/side-dish-backend/src/main/java/com/codesquad/team14/domain/Category.java
  BE/side-dish-backend/src/main/java/com/codesquad/team14/domain/Item.java
  BE/side-dish-backend/src/main/java/com/codesquad/team14/dto/CategoryDto.java
  BE/side-dish-backend/src/main/java/com/codesquad/team14/dto/DetailedItemDto.java
  BE/side-dish-backend/src/main/java/com/codesquad/team14/dto/ItemDto.java
  BE/side-dish-backend/src/main/java/com/codesquad/team14/exception/CategoryNotFoundException.java
  BE/side-dish-backend/src/main/java/com/codesquad/team14/exception/CustomExceptionHandler.java
  BE/side-dish-backend/src/main/java/com/codesquad/team14/exception/ErrorCode.java
  BE/side-dish-backend/src/main/java/com/codesquad/team14/exception/ErrorResponse.java
  BE/side-dish-backend/src/main/java/com/codesquad/team14/exception/ItemNotFoundException.java
  BE/side-dish-backend/src/main/java/com/codesquad/team14/repository/CategoryRepository.java
  BE/side-dish-backend/src/main/java/com/codesquad/team14/service/CategoryService.java
  BE/side-dish-backend/src/main/java/com/codesquad/team14/utils/Badge.java
  BE/side-dish-backend/src/main/java/com/codesquad/team14/utils/DeliveryType.java
  BE/side-dish-backend/src/main/resources/application.properties
  BE/side-dish-backend/src/main/resources/data.sql
  BE/side-dish-backend/src/main/resources/deploy.sh
  BE/side-dish-backend/src/main/resources/schema.sql
  BE/side-dish-backend/src/main/resources/setup.sql
  BE/side-dish-backend/src/main/resources/static/index.html
  BE/side-dish-backend/src/test/java/com/codesquad/team14/SideDishBackendApplicationTests.java
  BE/sidedish.mwb
Labels: review-BE

#37 [team6-BE] Jung, yeon 1차 PR
  .gitignore
  BE/.gitignore
  BE/README.md
  BE/build.gradle
  BE/gradle/wrapper/gradle-wrapper.jar
  BE/gradle/wrapper/gradle-wrapper.properties
  BE/gradlew
  BE/gradlew.bat
  BE/settings.gradle
  BE/src/main/java/sidedish/SidedishApplication.java
  BE/src/main/java/sidedish/controller/CategoryController.java
  BE/src/main/java/sidedish/controller/DishController.java
  BE/src/main/java/sidedish/controller/GlobalExceptionHandler.java
  BE/src/main/java/sidedish/controller/HomeController.java
  BE/src/main/java/sidedish/domain/Badge.java
  BE/src/main/java/sidedish/domain/Category.java
  BE/src/main/java/sidedish/domain/DetailImage.java
  BE/src/main/java/sidedish/domain/Dish.java
  BE/src/main/java/sidedish/domain/DishBuilder.java
  BE/src/main/java/sidedish/domain/Price.java
  BE/src/main/java/sidedish/domain/ThumbImage.java
  BE/src/main/java/sidedish/exception/CategoryNotFoundException.java
  BE/src/main/java/sidedish/exception/DishNotFoundException.java
  BE/src/main/java/sidedish/exception/NotFoundException.java
  BE/src/main/java/sidedish/repository/CategoryRepository.java
  BE/src/main/java/sidedish/repository/DishRepository.java
  BE/src/main/java/sidedish/service/CategoryService.java
  BE/src/main/java/sidedish/service/DishService.java
  BE/src/main/java/sidedish/service/TypeConvertUtils.java
  BE/src/main/java/sidedish/service/dto/CategoryDTO.java
  BE/src/main/java/sidedish/service/dto/DetailDishDTO.java
  BE/src/main/java/sidedish/service/dto/MainPageDishDTO.java
  BE/src/main/java/sidedish/service/dto/RequestDishDTO.java
  BE/src/main/resources/application.properties
  BE/src/main/resources/data.sql
  BE/src/main/resources/schema.sql
  README.md
Labels: review-BE

#24 [BE][Team-17][Robin, Cooper] 반찬가게 1차 PR 요청드립니다.
  backend/sidedish/.gitignore
  backend/sidedish/build.gradle
  backend/sidedish/gradle/wrapper/gradle-wrapper.jar
  backend/sidedish/gradle/wrapper/gradle-wrapper.properties
  backend/sidedish/gradlew
  backend/sidedish/gradlew.bat
  backend/sidedish/settings.gradle
  backend/sidedish/src/main/java/codsquad/team17/sidedish/SidedishApplication.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/config/WebConfig.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/controller/BestCategoryController.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/controller/DishCategoryController.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/controller/ItemDetailController.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/controller/OrderController.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/domain/BestCategory.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/domain/DishCategory.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/domain/Image.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/domain/Item.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/dto/BestCategoryDto.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/dto/DishCategoryDto.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/dto/ExceptionResponseDto.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/dto/ItemDetailDto.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/dto/ItemDto.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/dto/OrderDto.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/dto/RecommendedItemDto.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/exception/BestCategoryNotFoundException.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/exception/DishCategoryNotFoundException.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/exception/GlobalExceptionHandler.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/exception/ImageNotFoundException.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/exception/ItemNotFoundException.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/exception/ItemStockEmptyException.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/repository/BestCategoryRepository.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/repository/DishCategoryRepository.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/repository/ImageRepository.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/repository/ItemRepository.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/service/BestCategoryService.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/service/DishCategoryService.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/service/ItemDetailService.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/service/ItemService.java
  backend/sidedish/src/main/java/codsquad/team17/sidedish/service/OrderService.java
  backend/sidedish/src/main/resources/application.properties
  backend/sidedish/src/main/resources/data.sql
  backend/sidedish/src/main/resources/schema.sql
  backend/sidedish/src/test/java/codsquad/team17/sidedish/SidedishApplicationTests.java
Labels: review-BE

#52 [Team-21] RaQQoon Sidedish
  raqqoon-sidedish/.env
  raqqoon-sidedish/.gitignore
  raqqoon-sidedish/package-lock.json
  raqqoon-sidedish/package.json
  raqqoon-sidedish/server/routes/auth.js
  raqqoon-sidedish/server/server.js
  raqqoon-sidedish/src/App.js
  raqqoon-sidedish/src/components/Card/Card.jsx
  raqqoon-sidedish/src/components/Card/CarouselCard.jsx
  raqqoon-sidedish/src/components/Card/DefaultCard.jsx
  raqqoon-sidedish/src/components/Card/Img.jsx
  raqqoon-sidedish/src/components/Card/Info.jsx
  raqqoon-sidedish/src/components/Card/Price.jsx
  raqqoon-sidedish/src/components/Carousel/Carousel.jsx
  raqqoon-sidedish/src/components/Carousel/CarouselMain.jsx
  raqqoon-sidedish/src/components/Carousel/CarouselSection.jsx
  raqqoon-sidedish/src/components/Carousel/CategoryBtn.jsx
  raqqoon-sidedish/src/components/Header.jsx
  raqqoon-sidedish/src/components/Main.jsx
  raqqoon-sidedish/src/components/Nav/Dropdown.jsx
  raqqoon-sidedish/src/components/Nav/Login.jsx
  raqqoon-sidedish/src/components/Nav/LoginModal.jsx
  raqqoon-sidedish/src/components/Nav/Menu.jsx
  raqqoon-sidedish/src/components/Nav/MenuList.jsx
  raqqoon-sidedish/src/components/TabUI/TabBody.jsx
  raqqoon-sidedish/src/components/TabUI/TabMain.jsx
  raqqoon-sidedish/src/components/TabUI/TabUI.jsx
  raqqoon-sidedish/src/components/detail/Detail.jsx
  raqqoon-sidedish/src/components/detail/DetailCarousel.jsx
  raqqoon-sidedish/src/components/detail/DetailCarouselTitle.jsx
  raqqoon-sidedish/src/components/detail/DetailCloseButton.jsx
  raqqoon-sidedish/src/components/detail/DetailDelivery.jsx
  raqqoon-sidedish/src/components/detail/DetailImage.jsx
  raqqoon-sidedish/src/components/detail/DetailInfo.jsx
  raqqoon-sidedish/src/components/detail/DetailModal.jsx
  raqqoon-sidedish/src/components/detail/DetailOrder.jsx
  raqqoon-sidedish/src/components/detail/DetailPrice.jsx
  raqqoon-sidedish/src/components/detail/ImageData.jsx
  raqqoon-sidedish/src/components/detail/OrderButton.jsx
  raqqoon-sidedish/src/components/icons/Arrow.jsx
  raqqoon-sidedish/src/components/icons/GihubIcon.jsx
  raqqoon-sidedish/src/const.js
  raqqoon-sidedish/src/customHooks/useFetch.js
  raqqoon-sidedish/src/index.css
  raqqoon-sidedish/src/util/checkCardSize.js
  raqqoon-sidedish/src/util/getInfoBoxStyle.js
  raqqoon-sidedish/yarn.lock
Labels: review-FE

#8 [iOS][Neo & JeJe] MainUI and NetworkRequest
  Side-dish/Side-dish.xcodeproj/project.pbxproj
  Side-dish/Side-dish.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  Side-dish/Side-dish.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  Side-dish/Side-dish.xcodeproj/project.xcworkspace/xcuserdata/hoonhachoi.xcuserdatad/UserInterfaceState.xcuserstate
  Side-dish/Side-dish.xcodeproj/xcuserdata/hoonhachoi.xcuserdatad/xcschemes/xcschememanagement.plist
  Side-dish/Side-dish.xcodeproj/xcuserdata/jojung-yun.xcuserdatad/xcschemes/xcschememanagement.plist
  Side-dish/Side-dish/AppDelegate.swift
  Side-dish/Side-dish/Assets.xcassets/AccentColor.colorset/Contents.json
  Side-dish/Side-dish/Assets.xcassets/AppIcon.appiconset/Contents.json
  Side-dish/Side-dish/Assets.xcassets/Contents.json
  Side-dish/Side-dish/Assets.xcassets/EventColor.colorset/Contents.json
  Side-dish/Side-dish/Assets.xcassets/LaunchingColor.colorset/Contents.json
  Side-dish/Side-dish/Base.lproj/LaunchScreen.storyboard
  Side-dish/Side-dish/DIContainer.swift
  Side-dish/Side-dish/DataLayer/Model/Item.swift
  Side-dish/Side-dish/DataLayer/Model/SideDishes.swift
  Side-dish/Side-dish/DataLayer/Network/EndPoint.swift
  Side-dish/Side-dish/DataLayer/Network/HTTPMethod.swift
  Side-dish/Side-dish/DataLayer/Network/NetworkError.swift
  Side-dish/Side-dish/DataLayer/Network/NetworkManager.swift
  Side-dish/Side-dish/DomainLayer/Entity/SideDishManager.swift
  Side-dish/Side-dish/DomainLayer/UseCase/ImageUseCase.swift
  Side-dish/Side-dish/DomainLayer/UseCase/SideDishUseCase.swift
  Side-dish/Side-dish/Info.plist
  Side-dish/Side-dish/Main.storyboard
  Side-dish/Side-dish/PresentationLayer/View/AlertFactory.swift
  Side-dish/Side-dish/PresentationLayer/View/BadgeLabel.swift
  Side-dish/Side-dish/PresentationLayer/View/FoodCardCell.swift
  Side-dish/Side-dish/PresentationLayer/View/FoodCardCell.xib
  Side-dish/Side-dish/PresentationLayer/View/FoodCardHeaderView.swift
  Side-dish/Side-dish/PresentationLayer/View/FoodCardHeaderView.xib
  Side-dish/Side-dish/PresentationLayer/ViewController/SideDishViewController.swift
  Side-dish/Side-dish/PresentationLayer/ViewModel/SideDishViewModel.swift
  Side-dish/Side-dish/SceneDelegate.swift
Labels: review-iOS

#57 [Team23] 에러처리, 커스텀 훅, 깃헙 로그인, gcp 배포, css 작업
  banchan/.env
  banchan/.gitignore
  banchan/package-lock.json
  banchan/package.json
  banchan/public/GitHub-Mark.eps
  banchan/public/index.html
  banchan/src/App.jsx
  banchan/src/components/Callback.jsx
  banchan/src/components/Error.jsx
  banchan/src/components/LoginPage.jsx
  banchan/src/components/StateProvider.jsx
  banchan/src/components/componentUtils/Label.jsx
  banchan/src/components/componentUtils/Price.jsx
  banchan/src/components/componentUtils/button/IconButton.jsx
  banchan/src/components/componentUtils/button/TextButton.jsx
  banchan/src/components/componentUtils/card/Card.jsx
  banchan/src/components/componentUtils/card/Thumbnail.jsx
  banchan/src/components/componentUtils/mockData.js
  banchan/src/components/componentUtils/modal/ModalCard.jsx
  banchan/src/components/componentUtils/modal/products/ProductBuyInfo.jsx
  banchan/src/components/componentUtils/modal/products/ProductCount.jsx
  banchan/src/components/componentUtils/modal/products/ProductImage.jsx
  banchan/src/components/componentUtils/modal/products/ProductInformation.jsx
  banchan/src/components/componentUtils/modal/products/ProductMainInfo.jsx
  banchan/src/components/componentUtils/styles/common.jsx
  banchan/src/components/header/Header.jsx
  banchan/src/components/header/headerLeft/HeaderLeft.jsx
  banchan/src/components/header/headerLeft/HeaderNavbar.jsx
  banchan/src/components/header/headerLeft/NavListItems.jsx
  banchan/src/components/header/headerRight/HeaderRight.jsx
  banchan/src/components/main/MainPage.jsx
  banchan/src/components/main/carousel/CarouselSection.jsx
  banchan/src/components/main/carousel/CarouselSectionList.jsx
  banchan/src/components/main/tab/TabSection.jsx
  banchan/src/hooks/useFetch.jsx
  banchan/src/server/routes/auth.js
  banchan/src/server/server.js
  banchan/src/utils/variables.js
Labels: review-FE
